### ISSUE TITLE
Is it possible to add port to server argument?

### ISSUE THREAD

**Issue by joakimcarlsten** [helmutschneider/kent-dbcli#1]
I tried `./Kent.DbCli backup --server localhost:11433 ...` for those of us that are tunneling in. It didn't seem to work. Should it?

**Comment by helmutschneider** [comment]
Did you try `-S 'tcp:localhost,11433'`?

https://stackoverflow.com/a/6100072

**Comment by joakimcarlsten** [comment]
That worked fine, thanks!  💪
